enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  '@commitlint/cli@*':
    peerDependencies:
      '@types/node': '*'
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
